version: "3"
services:
    web:
        build: ./
        env_file: ".env"
        environment:
            APP_ENV: production
            REDIS_HOST: cache
        image: johnnyhuy/laravel:latest
        links:
            - "db:database"
        ports:
            - "80:80"
        restart: "no"
        volumes:
            - ./:/var/www/laravel
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_DATABASE: "homestead"
        restart: "no"
        ports:
            - 3307:3306
    cache:
        image: redis:alpine
    composer:
        command: [sh, -c, "composer install --no-dev"]
        image: composer
        restart: "no"
        volumes:
            - ./:/var/www/laravel
        working_dir: /var/www/laravel
    node:
        command: [sh, -c, "npm install && npm run prod"]
        image: node:alpine
        restart: "no"
        volumes:
            - ./:/var/www/laravel
        working_dir: /var/www/laravel
